version: '3'

services:
  wallabag:
    container_name: wallabag
    image: wallabag/wallabag
    networks: 
      - srv    
    expose:
      - 80
    volumes:
      - wallabag_data:/var/www/wallabag/data:rw
      - wallabag_images:/var/www/wallabag/web/assets/images:rw
    environment:
      - SYMFONY__ENV__DOMAIN_NAME="https://${HOST_WALLABAG}.${DOMAIN}"
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
    labels:
      - traefik.enable=true
      - traefik.http.routers.wallabag.rule=Host(`${HOST_WALLABAG}.${DOMAIN}`)
      - traefik.http.routers.wallabag.entrypoints=https
      - traefik.http.routers.wallabag.tls=true

volumes:
  wallabag_data: 
  wallabag_images:    
