version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443 
    environment:
      - DEFAULT_HOST=${HOST_WWW}.${DOMAIN}
      - DHPARAM_GENERATION=${LETSENCRYPT_GENERATE}
    networks:
      - srv             
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${ROOT_INSTALL}/data/nginx-proxy/certs:/etc/nginx/certs
      - ${ROOT_INSTALL}/data/nginx-proxy/dhparam:/etc/nginx/dhparam:rw
      - ${ROOT_INSTALL}/data/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - ${ROOT_INSTALL}/data/nginx-proxy/htpasswd:/etc/nginx/htpasswd

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${ROOT_INSTALL}/data/nginx-proxy/certs:/etc/nginx/certs:rw
      - ${ROOT_INSTALL}/data/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
      - acme:/etc/acme.sh
    networks: 
      - srv
      
volumes:
  dhparam:
  certs:
  acme:      