version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443 
    environment:
      - DEFAULT_HOST=${DOMAIN}
      - DHPARAM_GENERATION=false
    networks:
      - srv             
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${ROOT_INSTALL}/data/nginx-proxy/certs:/etc/nginx/certs
      - ${ROOT_INSTALL}/data/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro