#!/bin/bash
# override docker-compose
#   non executable YAML files are skipped (aka disabled services)
export DOCKER_COMPOSE_BIN='/usr/bin/docker compose'
docker-compose ()
{
    $DOCKER_COMPOSE_BIN $(find -name 'docker-compose*.yml' -type f -perm -u+x -printf '%p\t%d\n'  2>/dev/null | sort -n -k2 | cut -f 1 | awk '{print "-f "$0}') $@
}

#alias up='docker-compose --env-file /srv/selfhosting/.env up -d'
#alias down='docker-compose --env-file /srv/selfhosting/.env down'

# disable unused services 
chmod -x baikal/docker-compose.baikal.yml  
chmod -x posteio/docker-compose.posteio.yml 
chmod -x netdata/docker-compose.netdata.yml 
chmod -x photo/docker-compose.pigallery.yml 

# local testing
chmod -x traefik/docker-compose.traefik.yml

# live 
chmod -x traefik/docker-compose.traefik-local.yml 
