version: '3'

services:
  seafcli-photo:
    restart: always
    image: flowgunso/seafile-client
    container_name: seafcli-photo
    restart: unless-stopped
    environment:
      - SEAF_LIBRARY_UUID="${SEAFILE_PHOTO_LIBRARY}"
      - SEAF_SERVER_URL="https://${HOST_SEAFILE}.${DOMAIN}"
      - SEAF_USERNAME="${SEAFILE_REGULAR_USER}"
      - SEAF_PASSWORD="${SEAFILE_REGULAR_PASSWORD}"
    networks:
      - srv      
    volumes:
      - images:/library

  pigallery2:
    container_name: pigallery2
    environment:
      NODE_ENV: production
    image: bpatrik/pigallery2:latest
    networks:
      - srv    
    expose:
      - 80
    restart: unless-stopped
    volumes:
    - pigallery_config:/app/data/config:rw
    - pigallerydb_data:/app/data/db:rw
    - pigallery_tmp:/app/data/tmp:rw
    - images:/app/data/images:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.selfoss.rule=Host(`${HOST_PIGALLERY}.${DOMAIN}`)
      - traefik.http.routers.selfoss.entrypoints=websecure
      - traefik.http.routers.selfoss.tls=true
      - traefik.http.services.selfoss.loadbalancer.server.port=80

volumes:
  images:
  pigallerydb_data:
  pigallery_tmp:
  pigallery_config: