version: '3'

services:
  pigallery2:
    container_name: pigallery2
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${HOST_PIGALLERY}.${DOMAIN}
      LETSENCRYPT_HOST: ${HOST_PIGALLERY}.${DOMAIN}        
    image: bpatrik/pigallery2:1.9.0-alpine
    networks:
      - srv    
    expose:
      - 80
    restart: unless-stopped
    volumes:
    - pigallery_config:/app/data/config:rw
    - pigallerydb_data:/app/data/db:rw
    - pigallery_tmp:/app/data/tmp:rw
    - type: bind
      source: ${ROOT_INSTALL}/data/seafile-fuse
      target: /app/data/images
      bind:
        propagation: rslave
    privileged: true
    cap_add:
      - SYS_ADMIN
    healthcheck:
      disable: true

volumes:
  pigallerydb_data:
  pigallery_tmp:
  pigallery_config: