version: '3.8'

services:
  pigallery2:
    container_name: pigallery2
    environment:
      NODE_ENV: production
    image: bpatrik/pigallery2:1.9.0-alpine
    networks:
      - photo-frontend     
    expose:
      - 80
    restart: unless-stopped
    volumes:
    #/app/data/images
    - pigallery_config:/app/data/config:rw
    - pigallerydb_data:/app/data/db:rw
    - pigallery_tmp:/app/data/tmp:rw
    - type: bind
      source: ${ROOT_INSTALL}/data/seafile-fuse
      target: /seahub
      bind:
        propagation: rslave
    privileged: true
    cap_add:
      - SYS_ADMIN
    healthcheck:
      disable: true    
    labels:
      - traefik.enable=true
      - traefik.http.routers.photo.rule=Host(`${HOST_PIGALLERY}.${DOMAIN}`)
      - traefik.http.routers.photo.entrypoints=https
      - traefik.http.routers.photo.tls=true
      - traefik.docker.network=photo-frontend

networks:
  photo-frontend:
    name: photo-frontend
  photo-backend:
    name: photo-backend

volumes:
  pigallerydb_data:
  pigallery_tmp:
  pigallery_config:
