version: '3'

services:
  pigallery2:
    container_name: pigallery2
    environment:
      NODE_ENV: production
    image: bpatrik/pigallery2:1.9.0-alpine
    networks:
      - srv    
    expose:
      - 80
    restart: unless-stopped
    volumes:
    - pigallery_config:/app/data/config:rw
    - pigallerydb_data:/app/data/db:rw
    - pigallery_tmp:/app/data/tmp:rw
    - type: bind
      source: ${ROOT_INSTALL}/data/seafile-fuse
      target: /app/data/images
      bind:
        propagation: rslave
    privileged: true
    cap_add:
      - SYS_ADMIN
    healthcheck:
      disable: true    
    labels:
      - traefik.enable=true
      - traefik.http.routers.pigallery_config.rule=Host(`${HOST_PIGALLERY}.${DOMAIN}`)
      - traefik.http.routers.pigallery_config.entrypoints=websecure
      - traefik.http.routers.pigallery_config.tls=true
      - traefik.http.services.pigallery_config.loadbalancer.server.port=80

volumes:
  pigallerydb_data:
  pigallery_tmp:
  pigallery_config:
