version: '3.8'

services:
  lychee:
    container_name: lychee
    environment:
      - PHP_TZ=${TZ}
      - TIMEZONE=${TZ}        
    image: lycheeorg/lychee
    networks:
      - photo-frontend     
    expose:
      - 80
    restart: unless-stopped
    volumes:
      - ${lychee_conf}:/conf
      - ${lychee_uploads}:/uploads
      - ${lychee_sym}:/sym 
    labels:
      - traefik.enable=true
      - traefik.http.routers.photo.rule=Host(`${HOST_LYCHEE}.${DOMAIN}`)
      - traefik.http.routers.photo.entrypoints=https
      - traefik.http.routers.photo.tls=true
      - traefik.docker.network=photo-frontend

volumes:
  lychee_conf:
  lychee_uploads:
  lychee_sym:
