version: '3'

services:
  shaarli:
    container_name: shaarli
    image: shaarli/shaarli
    volumes:
      - shaarli-cache:/var/www/shaarli/cache
      - shaarli-data:/var/www/shaarli/data      
    networks:
      - srv
    restart: unless-stopped
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=${HOST_SHAARLI}.${DOMAIN}     
      - LETSENCRYPT_HOST=${HOST_SHAARLI}.${DOMAIN}

volumes:
  shaarli-data:
  shaarli-cache:      