version: '3'

services:

  seafcli-notes:
    image: snegov/seafile-client
    container_name: seafcli-notes
    restart: unless-stopped
    environment:
      - LIBRARY_ID=${SEAFILE_NOTES_LIBRARY}
      - SERVER_HOST=${HOST_SEAFILE}.${DOMAIN}
      - SERVER_PORT=443
      - USERNAME=${SEAFILE_REGULAR_USER}
      - PASSWORD=${SEAFILE_REGULAR_PASSWORD}
      - DATA_DIR=/library
    networks:
      - srv      
    volumes:
      - raneto_content:/library

  raneto:
    image: linuxserver/raneto
    container_name: raneto
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_INSTALL}/data/raneto:/config
      - raneto_content:/config/content
    expose:
      - 3000
    restart: unless-stopped
    networks: 
      - srv    
    labels:
      - traefik.enable=true
      - traefik.http.routers.raneto.rule=Host(`${HOST_RANETO}.${DOMAIN}`)
      - traefik.http.routers.raneto.entrypoints=websecure
      - traefik.http.routers.raneto.tls=true
      - traefik.http.services.raneto.loadbalancer.server.port=3000 

volumes:
  raneto_content: