version: '3'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.2
    command: --providers.docker --api.insecure=true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - srv
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.http.routers.service-http.rule=Host(${SITE})
      - traefik.http.routers.service-http.entrypoints=web
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.service-http.middlewares=https-redirect@docker
      - traefik.http.routers.service-https.rule=Host(${SITE})
      - traefik.http.routers.service-https.entrypoints=websecure
      - traefik.http.routers.service-https.tls=true
      - traefik.http.routers.service-https.tls.certresolver=letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/hosting/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - /srv/hosting/traefik/traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml:ro
      - /srv/hosting/traefik/acme.json:/acme.json
      - /srv/hosting/traefik/logs:/logs
