version: '3.8'

services:
  traefik:
    container_name: traefik-local
    image: traefik:v2.5.3
    profiles: ["testing"]   
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    expose:
      - 8080
    labels: 
      - traefik.enable=true      
    networks:
      - dmz
      - baikal-frontend
      - blog-frontend
      - deluge-frontend
      - dokuwiki-frontend
      - glances-frontend
      - netdata-frontend
      - photo-frontend
      - portainer-frontend
      - posteio-frontend
      - seafile-frontend
      - selfoss-frontend
      - shaarli-frontend
      - wallabag-frontend
      - wwww-frontend
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${ROOT_INSTALL}/selfhosting/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ${ROOT_INSTALL}/selfhosting/traefik/tls.yml:/etc/traefik/tls.yml
      - certs:/etc/ssl/traefik

  reverse-proxy-https-helper:
    image: alpine
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/cert.pem -O cert.pem
      && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik

volumes:
  certs: