version: '3'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.2
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
    ports:
      - 80:80
      - 8080:8080
    networks:
      - srv
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/hosting/traefik/logs:/logs
