[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  level = "WARNING"
  filePath = "/logs/traefik.log"
  format   = "json"

[accessLog]
  filePath = "/logs/access.log"
  format = "json"
  bufferingSize = 100

[api]
  dashboard = true
  debug = false
  insecure = true

[providers]
  [providers.docker]
    watch = true
    exposedByDefault = false
    swarmMode = false
    network = "srv"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers]
  [certificatesResolvers.letsencrypt]
    [certificatesResolvers.letsencrypt.acme]
      email = "kianby@madyanne.fr"
      caServer = "https://acme-v02.api.letsencrypt.org/directory"
      storage = "acme.json"
      keyType = "EC384"
      [certificatesResolvers.letsencrypt.acme.httpChallenge]
        entryPoint = "web"

