version: '3'

services:
  dokuwiki:
    image: linuxserver/dokuwiki
    container_name: dokuwiki
    restart: unless-stopped
    expose:
      - 80
    environment:
      - TZ=${TZ}
      - APP_URL=/ #optional      
    volumes:
      - ${ROOT_INSTALL}/data/dokuwiki:/config
    networks:
      - srv    
    labels:
      - traefik.enable=true
      - traefik.http.routers.dokuwiki.rule=Host(`${HOST_DOKUWIKI}.${DOMAIN}`)
      - traefik.http.routers.dokuwiki.entrypoints=websecure
      - traefik.http.routers.dokuwiki.tls=true
      - traefik.http.services.dokuwiki.loadbalancer.server.port=80


