version: '3'

services:

  seafcli-notes:
    image: snegov/seafile-client
    container_name: seafcli-notes
    restart: unless-stopped
    environment:
      - LIBRARY_ID=${SEAFILE_NOTES_LIBRARY}
      - SERVER_HOST=${HOST_SEAFILE}.${DOMAIN}
      - SERVER_PORT=443
      - USERNAME=${SEAFILE_REGULAR_USER}
      - PASSWORD=${SEAFILE_REGULAR_PASSWORD}
      - DATA_DIR=/library
    networks:
      - srv      
    volumes:
      - ${ROOT_INSTALL}/data/sync_notes:/library

  dokuwiki:
    image: 'docker.io/bitnami/dokuwiki:20200729-debian-10'
    container_name: dokuwiki
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - ${ROOT_INSTALL}/data/sync_notes/Notes:/bitnami/dokuwiki
    networks:
      - srv    
    labels:
      - traefik.enable=true
      - traefik.http.routers.dokuwiki.rule=Host(`${HOST_DOKUWIKI}.${DOMAIN}`)
      - traefik.http.routers.dokuwiki.entrypoints=websecure
      - traefik.http.routers.dokuwiki.tls=true
      - traefik.http.services.dokuwiki.loadbalancer.server.port=8080


