version: '3'

services:
  glances:
    container_name: glances
    image: vimagick/glances
    volumes:
      - glances_data:/etc/glances
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    pid: host
    restart: unless-stopped
    networks:
      - srv
    expose:
      - 61208
    labels:
      - traefik.enable=true
      - traefik.http.routers.glances.rule=Host(`${HOST_GLANCES}.${DOMAIN}`)
      - traefik.http.routers.glances.entrypoints=websecure
      - traefik.http.routers.glances.tls=true
      #- traefik.http.routers.glances.tls.certresolver=letsencrypt
      #- traefik.http.routers.glances.middlewares=redirect-to-https
      - traefik.http.services.glances.loadbalancer.server.port=61208

volumes:
  glances_data:
