version: '3'

services:
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: unless-stopped
    networks:
      - srv
    environment:
      DELUGE_LOGLEVEL: error
      PGID: ${PUID}
      PUID: ${PGID}
      TZ: ${TZ}
      UMASK_SET: '022'      
    expose:
      - 8112
    volumes:
      - deluge_config:/config:rw
      - deluge_downloads:/downloads:rw      
    labels:
      - traefik.enable=true
      - traefik.http.routers.deluge.rule=Host(`${HOST_WWW}.${DOMAIN}`) && PathPrefix(`${PATH_DELUGE}`) 
      - traefik.http.routers.deluge.entrypoints=websecure
      - traefik.http.routers.deluge.tls=true
      - traefik.http.services.deluge.loadbalancer.server.port=8112
      - traefik.http.routers.deluge.middlewares=delugeHeader,sameOriginHeader,auth
      - traefik.http.middlewares.auth.basicauth.users=${BASIC_AUTH}
      - traefik.http.middlewares.delugeHeader.headers.customrequestheaders.X-Deluge-Base=${PATH_DELUGE}/
      - traefik.http.middlewares.sameOriginHeader.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN
