version: '3'

services:
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: unless-stopped
    networks:
      - srv
    environment:
      DELUGE_LOGLEVEL: info
      TZ: ${TZ}    
    expose:
      - 8112
    ports:
      - ${DELUGE_TORRENT_PORT}:${DELUGE_TORRENT_PORT}/tcp
      - ${DELUGE_TORRENT_PORT}:${DELUGE_TORRENT_PORT}/udp
    volumes:
      - deluge_config:/config:rw
      - deluge_downloads:/downloads:rw
    environment:
      - VIRTUAL_HOST=${HOST_DELUGE}.${DOMAIN}
      - VIRTUAL_PORT=8112            

  torrent:
    container_name: torrent
    image: kianby/nginx-streaming
    restart: unless-stopped
    networks:
      - srv
    volumes:
      - deluge_downloads:/downloads:ro
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=${HOST_DELUGE_DOWNLOAD}.${DOMAIN}
      - HTTPS_METHOD=nohttps         
    
volumes:
  deluge_config:
  deluge_downloads: