version: '3'

services:

  seafcli-notes:
    image: snegov/seafile-client
    container_name: seafcli-notes
    restart: unless-stopped
    environment:
      - LIBRARY_ID=${SEAFILE_NOTES_LIBRARY}
      - SERVER_HOST=${HOST_SEAFILE}.${DOMAIN}
      - SERVER_PORT=443
      - USERNAME=${SEAFILE_REGULAR_USER}
      - PASSWORD=${SEAFILE_REGULAR_PASSWORD}
      - DATA_DIR=/library
    networks:
      - srv      
    volumes:
      - ${ROOT_INSTALL}/data/sync_notes:/library

  typemill:
    image: aberty/typemill-docker
    container_name: typemill
    environment:
      - TYPEMILL_UID=${PUID}
      - TYPEMILL_GID=${GUID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_INSTALL}/data/typemill/settings:/var/www/html/settings
      - ${ROOT_INSTALL}/data/typemill/cache:/var/www/html/cache
      - ${ROOT_INSTALL}/data/typemill/media:/var/www/html/media
      - ${ROOT_INSTALL}/data/sync_notes/Notes:/var/www/html/content
    expose:
      - 80
    restart: unless-stopped
    networks: 
      - srv    
    labels:
      - traefik.enable=true
      - traefik.http.routers.typemill.rule=Host(`${HOST_TYPEMILL}.${DOMAIN}`)
      - traefik.http.routers.typemill.entrypoints=websecure
      - traefik.http.routers.typemill.tls=true
      - traefik.http.services.typemill.loadbalancer.server.port=80 
