version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - srv
    restart: unless-stopped
    expose:
      - 9000    
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${SITE}`)
      - traefik.http.routers.portainer.entrypoints=web
      - traefik.http.services.portainer.loadbalancer.server.port=9000

volumes:
  portainer_data:
