version: '3'

services:
  poste-io:
    container_name: poste-io
    image: analogic/poste.io
    profiles: ["disabled"]
    volumes:
      - ${ROOT_INSTALL}/data/poste.io:/data
    environment:
      - TZ=${TZ}
      - HTTPS=OFF
    restart: unless-stopped
    ports:
      - "465:465"
      - "993:993"
      - "25:25"
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.posteio.rule=Host(`${HOST_MAIL}.${DOMAIN}`)
      - traefik.http.routers.posteio.entrypoints=https
      - traefik.http.routers.posteio.tls=true
      - traefik.docker.network=posteio-frontend
    networks:
      - posteio-frontend
    healthcheck:
      disable: true       
