version: '3'

services:
  wikijs:
    container_name: wikijs
    image: linuxserver/wikijs
    volumes:
      - ${ROOT_INSTALL}/data/wikijs/data:/data
      - ${ROOT_INSTALL}/data/wikijs/config:/config
    networks:
      - srv
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.http.routers.wikijs.rule=Host(`${HOST_WIKIJS}.${DOMAIN}`)
      - traefik.http.routers.wikijs.entrypoints=websecure
      - traefik.http.routers.wikijs.tls=true
      - traefik.http.services.wikijs.loadbalancer.server.port=3000       
        