version: "3.8"

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.16.9-rootless
    restart: unless-stopped
    volumes:
      - gitea_data:/var/lib/gitea
      - gitea_config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - source-frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`${HOST_GITEA}.${DOMAIN}`)
      - traefik.http.routers.gitea.entrypoints=https
      - traefik.http.routers.gitea.tls=true
      - traefik.docker.network=source-frontend
volumes:
  gitea_data:
  gitea_config:
